enabled: false

defaults:
  slo:
    availability: 99.9
    latency: 99
  alertThresholds:
    latencyMS: 100
    rate5xx: 0.05
    rate4xx: 5

namespace: observability

prependReleaseName: false

grafanaURL: ""

istioMetrics:
  enabled: true

nginxIngressMetrics:
  enabled: false
services: []
# - serviceName: "sample"
#   deploymentName: "sample"

#   slo: {}
#     # availability: 99.9
#     # latency: 99
 
#   alertThresholds: {}
#     # latencyMS: 100
#     # rate4xx: 5
#     # rate5xx: 0.05